server:
    port: 8888

spring:
    cloud:
        config:
            server:
                git:
                    uri: "https://github.com/markthemarkest/spring-config-piece"
                    searchPaths: config_server_files
